<div id="fb-wrap">
    <div class="fb">
        <div class="fb-head">
            <h1><?php echo $block->getTitle(); ?></h1>
            <p><?php echo $block->getDescription(); ?></p>
        </div>
        <div class="fb-body">
            <div
                class="fb-like"
                data-href="https://www.facebook.com/<?php echo $block->getFacebookURI(); ?>"
                data-layout="standard"
                data-action="like"
                data-show-faces="true"
                data-share="false">
            </div>
        </div>
        <div class="fb-footer">
            <a id="close" onclick="document.getElementById('fb-wrap').style.display='none';">
                <p><?php echo $block->getCloseText(); ?></p>
            </a>
        </div>
        <a class="close" onclick="document.getElementById('fb-wrap').style.display='none';">&times;</a>
    </div>
</div>
